apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector: { app: backend }
  ports:
    - name: http
      port: 5000
      targetPort: {{ .Values.backend.port }}