{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
type: kubernetes.io/dockerconfigjson
data:
  # pass base64 of the JSON to avoid YAML/CRLF headaches
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjsonB64 | required "imagePullSecret.dockerconfigjsonB64 missing" | quote }}
{{- end }}