# charts/pdf-app/templates/pull-secret.yaml
{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
{{ .Values.imagePullSecret.dockerconfigjson | nindent 4 }}
{{- end }}