{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {{- /* Jenkins injects raw JSON here at install/upgrade time */ -}}
    {{ .Values.imagePullSecret.dockerconfigjson | nindent 4 }}
{{- end }}